version: '3.9'

services:

  coturn:
    restart: always
    build: .
    network_mode: host
    # ports:
      # ## STUN/TURN
      # - "3478:3478"
      # - "3478:3478/udp"
      # - "3479:3479"
      # - "3479:3479/udp"
      # ## STUN/TURN SSL
      # - "5349:5349"
      # - "5349:5349/udp"
      # - "5350:5350"
      # - "5350:5350/udp"
      # ## Relay ports
      # #- "49152-65535:49152-65535"
      # #- "49152-65535:49152-65535/udp"
    volumes:
      - "./coturn/turnserver.conf:/etc/turnserver.conf:ro"
      - "coturn-db:/var/lib/coturn"
      - ./synapse:/synapse
      - ./ssl:/etc/ssl:ro

volumes:
  coturn-db:
